version: '3.4'

services:
  sourcingdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  sourcingsqldb:
    image: mcr.microsoft.com/mssql/server

  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcing.Products/Dockerfile

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: Esourcing.Sourcing/Dockerfile

  esourcing.order:
    image: ${DOCKER_REGISTRY-}esourcingorder
    build:
      context: .
      dockerfile: ESourcing.Order/Dockerfile

  esourcing.apigateway:
    image: ${DOCKER_REGISTRY-}esourcingapigateway
    build:
      context: .
      dockerfile: ESourcing.APIGateway/Dockerfile

